IBM/core-dump-handler

- charts/templates/daemonset.yaml
- charts/templates/pv.yaml
- charts/templates/pvc.yaml
- charts/values.yaml
Add ability to configure:
* Affinity & tolerations for the daemonset's pods
* PV size
Default values have been assigned so that the chart's default behaviour remains the same.
> Add more chart configuration options

- Cargo.lock
- charts/templates/daemonset.yaml
- charts/values.yaml
- core-dump-agent/Cargo.toml
- core-dump-agent/src/main.rs
- core-dump-client/src/main.rs
- core-dump-composer/src/main.rs
This pr adds a flag to enable the core dump composer to not try and get the meta data from crictl. 
This will make the EKS environment cleaner and also allow for running the binaries in none container scenarios is required.
There is also a fix to clean up the suid properly
> Add support for ignoring crictl 

- charts/templates/_helpers.tpl
- charts/templates/clusterrole.yaml
- charts/templates/daemonset.yaml
- charts/templates/pvc.yaml
- charts/templates/secrets.yaml
- charts/values.yaml
- core-dump-agent/src/main.rs
This allows overriding the env-vars of the daemonset and disabling of builting secret handling.
> Allow env-var overriding

- Cargo.lock
- charts/core-dump-handler/Chart.yaml
- charts/core-dump-handler/ci/inotify-manage-store.yaml
- charts/core-dump-handler/ci/schedule-no-manage-store.yaml
- charts/core-dump-handler/ci/tolerations.yaml
- charts/core-dump-handler/values.schema.json
- charts/core-dump-handler/values.yaml
- core-dump-agent/Cargo.toml
- core-dump-agent/src/main.rs
- core-dump-agent/tests/basic.rs
Fix for https://github.com/IBM/core-dump-handler/issues/62
Bump latest version of tokio-cron-scheduler https://github.com/mvniekerk/tokio-cron-scheduler/releases/tag/0.4
> fix!: Update schema and bump tokio scheduler version

- Cargo.lock
- charts/core-dump-handler/README.md
- charts/core-dump-handler/templates/daemonset.yaml
- charts/core-dump-handler/values.aws.yaml
- core-dump-agent/src/main.rs
use a node or config based creds when not supplied explicitly
fixes: #75
> fix hardcoded s3 creds

- charts/core-dump-handler/README.md
- charts/core-dump-handler/templates/secrets.yaml
- charts/core-dump-handler/templates/serviceaccount.yaml
- charts/core-dump-handler/values.aws.sts.yaml
- charts/core-dump-handler/values.schema.json
- charts/core-dump-handler/values.yaml
- core-dump-agent/src/main.rs
Hello, this patch makes it possible to use the preferred way to authenticate pods with AWS STS ([see here](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)).
tl;dr without setting a keypair, but instead loading tokens from a mounted file handled by an admission controller.
I've tested it on our EKS deployment before submitting this PR.
> Add ability to authenticate against AWS via STS

- charts/core-dump-handler/templates/openshift-scc.yaml
Restrict scc unnecessary permissions when running in OpenShift.
> Restrict OpenShift SecurityContextConstraints

- core-dump-composer/src/config.rs
- core-dump-composer/src/main.rs
This allow use `podname` parameter in the filename template
> add podname parameter to allow use it in the filename template

- core-dump-composer/src/config.rs
This fix early load .env file to override some variables like FILENAME_TEMPLATE
> fix loading .env by composer

- charts/core-dump-handler/README.md
- charts/core-dump-handler/ci/inotify-manage-store.yaml
- charts/core-dump-handler/ci/interval-manage-store.yaml
- charts/core-dump-handler/ci/schedule-no-manage-store.yaml
- charts/core-dump-handler/ci/tolerations.yaml
- charts/core-dump-handler/templates/daemonset.yaml
- charts/core-dump-handler/values.schema.json
- charts/core-dump-handler/values.yaml
- core-dump-agent/src/main.rs
When `DEPLOY_CRIO_CONFIG` is `true`, both `image-endpoint` and `runtime-endpoint` are generated as hard coded values [here](https://github.com/IBM/core-dump-handler/blob/a67034ad7e807df956947b74b770a978235bf27b/core-dump-agent/src/main.rs#L422). This PR is to make them optionally configurable. To configure it, `daemonset.crioEndpoint` can now be set in `values.yaml`, which translates to the `CRIO_ENDPOINT` environment variable in the daemonset.
Found this useful on setups that have dockershim. The default is still set to `unix:///run/containerd/containerd.sock`, so this should be backwards compatible.
> configurable crictl endpoint

- charts/core-dump-handler/README.md
- charts/core-dump-handler/templates/daemonset.yaml
- charts/core-dump-handler/values.aws.bottlerocket.yaml
- charts/core-dump-handler/values.schema.json
- charts/core-dump-handler/values.yaml
Bottlerocket mounts the containerd socket under /run/dockershim.sock,
which does not appear to be part of the standard privileged container.
Add
mountContainerRuntimeEndpoint: false
hostContainerRuntimeEndpoint: "/run/containerd/containerd.sock"
as chart defaults.
https://github.com/bottlerocket-os/bottlerocket/commit/91810c85b83ff4c3660b496e243ef8b55df0973b
https://github.com/bottlerocket-os/bottlerocket/issues/2212
> helm daemonset: Allow mounting the host container runtime socket

- core-dump-composer/mocks/crictl-timeout.sh
- core-dump-composer/src/config.rs
- core-dump-composer/src/main.rs
- core-dump-composer/tests/timeout.rs
> Implement timeout handling

- Cargo.lock
- charts/core-dump-handler/Chart.yaml
- charts/core-dump-handler/values.yaml
- core-dump-composer/Cargo.toml
Signed-off-by: Anthony Whalley <anton@venshare.com>
> fix: update logger and ready release

- core-dump-composer/src/config.rs
- core-dump-composer/src/main.rs
This MR fixes two issues seen in a production environment:
* We have the problem that big core dumps were corrupted which can be fixed by using `io::copy` instead of  the manual read/write logic. It's unclear to me why because I am not a Rust guru. Another problem with big core dumps was that they turned out to be corrupted when compression is enabled. The `-D` flag works well for that and just stores data as-is in the resulting ZIP file.
* The `counter` variable to gather information on containers was never incremented thus overwriting previous container information.
> Allow to disable ZIP compression & fix bug in overwriting info files 

- Cargo.lock
- FAQ.md
- charts/core-dump-handler/README.md
- charts/core-dump-handler/templates/daemonset.yaml
- charts/core-dump-handler/values.schema.json
- charts/core-dump-handler/values.yaml
- core-dump-agent/src/main.rs
- core-dump-agent/tests/basic.rs
- core-dump-composer/Cargo.toml
- core-dump-composer/src/config.rs
- core-dump-composer/src/main.rs
- core-dump-composer/tests/timeout.rs
@timbuchwaldt I've moved the setting of the timeout out of the composer arguments and into the chart so it's setup as an environment variable called `TIMEOUT`.
https://github.com/IBM/core-dump-handler/commit/867b4a797a9517aefc062839be48cf97214446c6#diff-41993b17674b907eda9d68b0aabdb0fe6cca65177bc94b74cba88ffc23932dc2R30
@stonemaster The disable compression `-D` has also been removed and added an environment variable called `COMPRESSION` to the composer config
https://github.com/IBM/core-dump-handler/commit/867b4a797a9517aefc062839be48cf97214446c6#diff-41993b17674b907eda9d68b0aabdb0fe6cca65177bc94b74cba88ffc23932dc2R31
The image is building here: https://quay.io/repository/icdh/core-dump-handler/build/b50f285f-8120-4a84-ad7e-beb3358afe97 
Once that is compete you should be able to checkout …
> Add environment variables to Chart for Timeout and No Compression

- Cargo.lock
- charts/core-dump-handler/values.yaml
- core-dump-agent/src/main.rs
- integration/run-ibm.sh
Due to [updates in the scheduler](https://github.com/mvniekerk/tokio-cron-scheduler/releases) the scheduler was failing on the first call to the scheduled poll.
This wasn't caught in integration testing as the server would restart the agent pod and this would initiate a sweep that would allow the test to pass. 
This update now maps to the implementation in the tokio-cron-scheduler examples and uses a loop to prevent the agent from falling through while it waits for the async handles to complete.
> Scheduler fix

- .gitignore
- charts/core-dump-handler/templates/daemonset.yaml
- charts/core-dump-handler/values.minikube.yaml
- Fix flag control in chart template for event source feature
- Fix missing `pullPolicy` mapping from values to template
- Add minikube sample values to play with it
- Update gitignore
> Fix event sourcing setup in chart templates

- charts/core-dump-handler/templates/daemonset.yaml
In charts, pullSecrets is present in values.yaml but is not being used inside templates/daemonset.yaml.
Signed-off-by: Rohit Saini <rsaini@a5gnet.com>
> issue129: handle pullSecrets inside daemonset.yaml

- charts/core-dump-handler/README.md
- charts/core-dump-handler/templates/_helpers.tpl
- charts/core-dump-handler/templates/daemonset.yaml
- charts/core-dump-handler/values.minikube.yaml
- charts/core-dump-handler/values.schema.json
- charts/core-dump-handler/values.yaml
- Helm chart now supports injecting sidecar containers, adding envvars with `envFrom` instructions to read either configMaps as well as secrets.
- Add sample sidecar to minikube values that prints the event file to stdout
> Add more parameters to helm chart

- charts/core-dump-handler/README.md
- charts/core-dump-handler/templates/daemonset.yaml
- charts/core-dump-handler/values.minikube.yaml
- charts/core-dump-handler/values.schema.json
- charts/core-dump-handler/values.yaml
@No9 one more field to release to helm chart. I notice that rolling changes for larger K8s cluster (100+ nodes) may take a while, so in order to allow users to speed rollouts, they can now set other update strategy.
> Add updateStrategy to helm chart

- core-dump-composer/tests/default.rs
- core-dump-composer/tests/imagecommand.rs
- core-dump-composer/tests/namespacedfiles.rs
- core-dump-composer/tests/timeout.rs
- core-dump-composer/tests/withoutcrio.rs
When running the tests for the Core Dump Composer the error output was not being printed. This was making things a little difficult to track down where the tests might be failing if the Composer was hitting an error path.
This PR just adds `println!("{}", String::from_utf8_lossy(&cdc.stderr));` underneath all locations where `cdc.stdout` is already getting printed in the tests for the Composer
> Update CDC tests to print out the stderr when tests fail

- core-dump-agent/src/main.rs
Hi @No9.
I found that the chart value `composer.logLength` doesn't affect to the composer's actual setting value `LOG_LENGTH`.
Then it's just used the default value 500 even though I specify it like this.
```
helm install core-dump-handler . --set composer.logLength=10
``` 
Because core-dump-agent doesn't read the environment variable "COMP_LOG_LENGTH" passed from `daemonset.yaml`.
> Chart value "composer.logLength" doesn't affect.

- charts/core-dump-handler/README.md
- charts/core-dump-handler/templates/sa-token-secret.yaml
- charts/core-dump-handler/values.aws.yaml
- charts/core-dump-handler/values.yaml
Adds a new secret to be compatible with EKS >= 1.24 (see https://aws.github.io/aws-eks-best-practices/security/docs/iam/). 
This closes https://github.com/IBM/core-dump-handler/issues/143 and closes https://github.com/IBM/core-dump-handler/issues/140. 
Open design questions:
* ~put token secret in dedicated file?~
* ~make secret name configurable?~
* add token conditionally (for example only for versions later than 1.24 based on [`KubeVersion`](https://helm.sh/docs/chart_template_guide/builtin_objects/)?
* ~add specific flag to toggle token secret creation?~
Let me know what you think :smiley:
> Add service account token secret

- Cargo.lock
- charts/core-dump-handler/README.md
- charts/core-dump-handler/ci/inotify-manage-store.yaml
- charts/core-dump-handler/ci/interval-manage-store.yaml
- charts/core-dump-handler/ci/schedule-no-manage-store.yaml
- charts/core-dump-handler/templates/daemonset.yaml
- charts/core-dump-handler/values.schema.json
- charts/core-dump-handler/values.yaml
- core-dump-agent/Cargo.toml
- core-dump-agent/src/main.rs
- core-dump-agent/tests/basic.rs
- core-dump-composer/Cargo.toml
- core-dump-composer/mocks/crictl-gatherprocfiles.sh
- core-dump-composer/mocks/proc/117/auxv
- core-dump-composer/mocks/proc/117/cmdline
- core-dump-composer/mocks/proc/117/environ
- core-dump-composer/mocks/proc/117/maps
- core-dump-composer/mocks/proc/117/status
- core-dump-composer/src/config.rs
- core-dump-composer/src/main.rs
- core-dump-composer/tests/gatherprocfiles.rs
Running breakpads core2md out-of-process requires some files from the /proc/$pid folder to be able to successfully generate enough information.
This change enables gathering of those said files to be able to support that flow. It is hidden behind a feature flag and its disabled by default so that the behavior of the composer is same as before.
This feature is ment to grab the minimum files needed to be able to generate minidumps. So heap data will be omitted and such.
> Add support for gathering proc files necessary to convert coredump to minidump

- charts/core-dump-handler/README.md
- charts/core-dump-handler/templates/daemonset.yaml
- charts/core-dump-handler/values.schema.json
- charts/core-dump-handler/values.yaml
to address https://github.com/IBM/core-dump-handler/issues/161
> Add pod annotations
